# 财务报表列名映射配置文件（东方财富API版本）
# 基于东方财富API (stock_*_by_report_em) 的字段名
# 更新日期: 2026-01-28

common:
  SECURITY_CODE: stock_code
  REPORT_DATE: report_date
  NOTICE_DATE: announcement_date
balance_sheet:
  MONETARYFUNDS: monetary_capital
  SETTLE_RESERVES: settlement_provisions
  LEND_FUND: loans_to_other_banks
  TRADABLE_FNNCL_ASSETS: trading_financial_assets
  BUY_RESALE_FINASSET: financial_assets_purchased_for_resale
  DERIVE_FINASSET: derivative_financial_assets
  NOTE_ACCOUNTS_RECE: notes_and_accounts_receivable
  NOTE_RECE: notes_receivable
  ACCOUNTS_RECE: accounts_receivable
  FINANCE_RECE: receivables_financing
  PREPAYMENT: prepayments
  DIVIDEND_RECE: dividends_receivable
  INTEREST_RECE: interest_receivable
  PREMIUM_RECE: insurance_premiums_receivable
  REINSURE_RECE: reinsurance_receivables
  REINSURE_CONTRACT_RESERVES_RECE: reinsurance_contract_reserves_receivable
  EXPORT_REFUND_RECE: export_tax_rebates_receivable
  SUBSIDY_RECE: subsidies_receivable
  DEPOSIT_RECE: deposits_receivable
  INTERNAL_RECE: internal_receivables
  OTHER_RECE: other_receivables
  OTHER_RECE_TOTAL: other_receivables_total
  INVENTORIES: inventories
  HELD_FOR_SALE_ASSETS: assets_held_for_sale
  PREPAID_EXPENSE: prepaid_expenses
  CURRENT_ASSET_PENDING_DISPOSAL: current_assets_pending_disposal
  NONCURRENT_ASSET_1YEAR: non_current_assets_due_within_one_year
  CURRENT_ASSET_OTHER: other_current_assets
  TOTAL_CURRENT_ASSETS: total_current_assets
  NONCURRENT_ASSET_BALANCE: non_current_assets
  LOAN_ADVANCE: loans_and_advances
  CREDITOR_INVEST: debt_investments
  OTHER_CREDITOR_INVEST: other_debt_investments
  FVOCI_FINASSET: financial_assets_at_fvoci
  AMORTIZE_COST_FINASSET: financial_assets_at_amortized_cost
  AVAILABLE_SALE_FINASSET: available_for_sale_financial_assets
  LONG_TERM_EQUITY_INVEST: long_term_equity_investments
  INVEST_REAL_ESTATE: investment_property
  LONG_TERM_RECE: long_term_receivables
  OTHER_EQUITY_INVEST: other_equity_instrument_investments
  OTHER_NONCURRENT_FINASSET: other_non_current_financial_assets
  OTHER_LONG_TERM_INVEST: other_long_term_investments
  FIXED_ASSET_ORIGINAL_VALUE: fixed_assets_original_value
  ACCUMULATED_DEPRECIATION: accumulated_depreciation
  FIXED_ASSET_NET_VALUE: fixed_assets_net_value
  FIXED_ASSET_IMPAIRMENT: fixed_assets_impairment_provision
  CIP_TOTAL: construction_in_progress_total
  CIP: construction_in_progress
  PROJECT_MATERIAL: construction_materials
  FIXED_ASSET: fixed_assets_net
  FIXED_ASSET_DISPOSAL: fixed_assets_disposal
  FIXED_ASSET_DISPOSAL_TOTAL: fixed_assets_and_disposal_total
  PRODUCTIVE_BIOLOGY_ASSET: productive_biological_assets
  CONSUMPTIVE_BIOLOGICAL_ASSET: consumptive_biological_assets
  OIL_GAS_ASSET: oil_and_gas_assets
  CONTRACT_ASSET: contract_assets
  USERIGHT_ASSET: right_of_use_assets
  INTANGIBLE_ASSET: intangible_assets
  DEVELOP_EXPENSE: development_expenditure
  GOODWILL: goodwill
  LONG_PREPAID_EXPENSE: long_term_deferred_expenses
  SPLIT_SHARE_CIRCULATION_RIGHT: split_share_structure_circulation_rights
  DEFER_TAX_ASSET: deferred_tax_assets
  NONCURRENT_ASSET_OTHER: other_non_current_assets
  TOTAL_NONCURRENT_ASSETS: total_non_current_assets
  TOTAL_ASSETS: total_assets
  CURRENT_LIAB_BALANCE: current_liabilities
  SHORT_TERM_LOAN: short_term_borrowings
  BORROW_CENTRAL_BANK: borrowings_from_central_bank
  ACCEPT_DEPOSIT_INTERBANK: deposits_from_customers_and_banks
  BORROW_FUND: borrowings_from_other_banks
  TRADABLE_FNNCL_LIAB: trading_financial_liabilities
  DERIVE_FINLIAB: derivative_financial_liabilities
  NOTE_ACCOUNTS_PAYABLE: notes_and_accounts_payable
  NOTES_PAYABLE: notes_payable
  ACCOUNTS_PAYABLE: accounts_payable
  ADVANCE_RECEIVABLES: advances_from_customers
  CONTRACT_LIAB: contract_liabilities
  SELL_REPO_FINASSET: financial_assets_sold_for_repurchase
  FEE_COMMISSION_PAYABLE: fees_and_commissions_payable
  EMPL_BEN_PAYABLE: employee_benefits_payable
  TAXES_SURCHARGES_PAYABLE: taxes_payable
  INTEREST_PAYABLE: interest_payable
  DIVIDEND_PAYABLE: dividends_payable
  DEPOSIT_PAYABLE: deposits_payable
  INTERNAL_PAYABLE: internal_payables
  OTHER_PAYABLE: other_payables
  OTHER_PAYABLE_TOTAL: other_payables_total
  OTHER_TAX_PAYABLE: other_taxes_payable
  GUARANTEE_LIABILITY_RESERVES: guarantee_liability_reserves
  REINSURE_PAYABLE: reinsurance_payables
  INSURANCE_CONTRACT_RESERVES: insurance_contract_reserves
  AGENT_TRADE_SECURITY: securities_trading_agency_payables
  AGENT_UNDERWRITE_SECURITY: securities_underwriting_agency_payables
  INTERNATIONAL_SETTLEMENT: international_settlement
  DOMESTIC_SETTLEMENT: domestic_settlement
  ACCRUED_EXPENSE: accrued_expenses
  ESTIMATED_CURRENT_LIAB: estimated_current_liabilities
  SHORT_TERM_BOND_PAYABLE: short_term_bonds_payable
  HELD_FOR_SALE_LIAB: liabilities_held_for_sale
  DEFER_INCOME_1YEAR: deferred_revenue_due_within_one_year
  NONCURRENT_LIAB_1YEAR: non_current_liabilities_due_within_one_year
  CURRENT_LIAB_OTHER: other_current_liabilities
  TOTAL_CURRENT_LIAB: total_current_liabilities
  NONCURRENT_LIAB_BALANCE: non_current_liabilities
  LONG_TERM_LOAN: long_term_borrowings
  BOND_PAYABLE: bonds_payable
  BOND_PAYABLE_PREFERRED_STOCK: bonds_payable_preferred_stock
  BOND_PAYABLE_PERPETUAL_BOND: bonds_payable_perpetual_bonds
  LEASE_LIAB: lease_liabilities
  LONG_TERM_EMPL_BEN_PAYABLE: long_term_employee_benefits_payable
  LONG_TERM_PAYABLE: long_term_payables
  LONG_TERM_PAYABLE_TOTAL: long_term_payables_total
  SPECIAL_PAYABLE: special_payables
  ESTIMATED_NONCURRENT_LIAB: estimated_non_current_liabilities
  DEFER_INCOME: long_term_deferred_revenue
  DEFER_TAX_LIAB: deferred_tax_liabilities
  NONCURRENT_LIAB_OTHER: other_non_current_liabilities
  TOTAL_NONCURRENT_LIAB: total_non_current_liabilities
  TOTAL_LIABILITIES: total_liabilities
  EQUITY_BALANCE: owners_equity
  SHARE_CAPITAL: paid_in_capital
  OTHER_EQUITY_TOOLS: other_equity_instruments
  PREFERRED_STOCK: preferred_stock
  PERPETUAL_BOND: perpetual_bonds
  CAPITAL_RESERVE: capital_reserve
  TREASURY_SHARE: less_treasury_stock
  OTHER_COMPREHENSIVE_INCOME: other_comprehensive_income
  SPECIAL_RESERVE: special_reserve
  SURPLUS_RESERVE: surplus_reserve
  GENERAL_RISK_RESERVE: general_risk_reserve
  UNRECOGNIZED_INVEST_LOSS: unrecognized_investment_losses
  RETAINED_EARNINGS: retained_earnings
  ASSIGN_CASH_DIVIDEND: proposed_cash_dividends
  CONVERT_DIFF: foreign_currency_translation_difference
  EQUITY_PARENT_COMPANY: equity_attributable_to_parent_company
  MINORITY_EQUITY: minority_interests
  TOTAL_EQUITY: total_owners_equity
  TOTAL_LIAB_AND_EQUITY: total_liabilities_and_owners_equity
income_statement:
  TOTAL_OPERATE_INCOME: total_operating_revenue
  OPERATE_INCOME: operating_revenue
  INTEREST_INCOME: interest_income
  EARNED_PREMIUM: earned_premiums
  FEE_COMMISSION_INCOME: fees_and_commissions_income
  REAL_ESTATE_SALES_INCOME: real_estate_sales_revenue
  OTHER_BUSINESS_INCOME: other_business_revenue
  TOTAL_OPERATE_COST: total_operating_costs
  OPERATE_COST: operating_costs
  FEE_COMMISSION_EXPENSE: fees_and_commissions_expenses
  REAL_ESTATE_SALES_COST: real_estate_sales_costs
  SURRENDER_VALUE: surrender_value
  NET_CLAIM_EXPENSE: net_claims_paid
  NET_INSURANCE_CONTRACT_RESERVE: net_insurance_contract_reserves
  POLICY_DIVIDEND_EXPENSE: policy_dividend_expenses
  REINSURANCE_COST: reinsurance_expenses
  OTHER_BUSINESS_COST: other_business_costs
  OPERATE_TAX_ADD: taxes_and_surcharges
  RD_EXPENSE: rd_expenses
  SALE_EXPENSE: selling_expenses
  MANAGE_EXPENSE: administrative_expenses
  FINANCE_EXPENSE: financial_expenses
  INTEREST_EXPENSE: interest_expenses
  INTEREST_EXPENDITURE: interest_expenditure
  INVEST_INCOME: investment_income
  INVEST_JOINT_VENTURE_INCOME: investment_income_from_associates_and_joint_ventures
  AMORTIZE_COST_FINASSET_DERECOGNIZE_INCOME: gain_on_derecognition_of_financial_assets_at_amortized_cost
  EXCHANGE_INCOME: foreign_exchange_gains
  NET_OPEN_HEDGE_INCOME: net_open_hedge_gains
  FAIR_VALUE_CHANGE_INCOME: fair_value_change_gains
  FUTURES_INCOME: futures_gains_losses
  CUSTODY_INCOME: custody_income
  SUBSIDY_INCOME: subsidy_income
  OTHER_INCOME: other_gains
  ASSET_IMPAIRMENT_LOSS: asset_impairment_losses
  CREDIT_IMPAIRMENT_LOSS: credit_impairment_losses
  OTHER_BUSINESS_PROFIT: other_business_profits
  ASSET_DISPOSAL_INCOME: asset_disposal_gains
  OPERATE_PROFIT: operating_profit
  NONBUSINESS_INCOME: non_operating_income
  NONCURRENT_ASSET_DISPOSAL_GAIN: non_current_asset_disposal_gains
  NONBUSINESS_EXPENSE: non_operating_expenses
  NONCURRENT_ASSET_DISPOSAL_LOSS: non_current_asset_disposal_losses
  TOTAL_PROFIT: total_profit
  INCOME_TAX: income_tax_expense
  UNRECOGNIZED_INVEST_LOSS: unrecognized_investment_losses
  NETPROFIT: net_profit
  CONTINUED_NETPROFIT: net_profit_from_continuing_operations
  DISCONTINUED_NETPROFIT: net_profit_from_discontinued_operations
  PARENT_NETPROFIT: net_profit_attributable_to_parent_company
  MERGED_NETPROFIT_BEFORE: net_profit_of_acquiree_before_merger
  MINORITY_INCOME: minority_interests_profit_loss
  OTHER_COMPREHENSIVE_INCOME: other_comprehensive_income
  PARENT_OCI: other_comprehensive_income_attributable_to_parent
  OCI_NOT_RECLASSIFIED: oci_not_reclassified_to_profit_loss
  REMEASURE_DEFINED_BENEFIT_PLAN: remeasurement_of_defined_benefit_plans
  EQUITY_METHOD_OCI_NOT_RECLASSIFIED: oci_under_equity_method_not_reclassified
  OTHER_EQUITY_INVEST_FV_CHANGE: fair_value_change_of_other_equity_instruments
  OWN_CREDIT_RISK_FV_CHANGE: fair_value_change_of_own_credit_risk
  OCI_RECLASSIFIED: oci_reclassified_to_profit_loss
  EQUITY_METHOD_OCI_RECLASSIFIED: oci_under_equity_method_reclassified
  AFS_FINASSET_FV_CHANGE: fair_value_change_of_afs_financial_assets
  OTHER_CREDITOR_INVEST_FV_CHANGE: fair_value_change_of_other_debt_investments
  FINASSET_RECLASSIFIED_TO_OCI: financial_assets_reclassified_to_oci
  OTHER_CREDITOR_INVEST_CREDIT_IMPAIRMENT: credit_impairment_of_other_debt_investments
  HTM_RECLASSIFIED_TO_AFS: htm_reclassified_to_afs_gains_losses
  CASH_FLOW_HEDGE_RESERVE: cash_flow_hedge_reserve
  CASH_FLOW_HEDGE_EFFECTIVE_PORTION: effective_portion_of_cash_flow_hedge
  CONVERT_DIFF: foreign_currency_translation_difference
  OTHER: other
  MINORITY_OCI: other_comprehensive_income_attributable_to_minority
  TOTAL_COMPREHENSIVE_INCOME: total_comprehensive_income
  PARENT_TCI: total_comprehensive_income_attributable_to_parent
  MINORITY_TCI: total_comprehensive_income_attributable_to_minority
  BASIC_EPS: basic_earnings_per_share
  DILUTED_EPS: diluted_earnings_per_share
cash_flow_statement:
  OPERATE_CASH_FLOW_BALANCE: cash_flows_from_operating_activities
  SALES_SERVICES: cash_received_from_sale_of_goods_and_services
  DEPOSIT_INTERBANK_ADD: net_increase_in_customer_deposits_and_interbank_deposits
  BORROW_CENTRAL_BANK_ADD: net_increase_in_borrowings_from_central_bank
  BORROW_FINANCE_INSTITUTION_ADD: net_increase_in_borrowings_from_other_financial_institutions
  RECEIVE_ORIGINAL_INSURANCE_PREMIUM: cash_received_from_original_insurance_premiums
  RECEIVE_REINSURANCE_NET: net_cash_received_from_reinsurance
  INSURED_DEPOSIT_INVEST_ADD: net_increase_in_policyholder_deposits_and_investments
  DISPOSAL_TRADABLE_FINASSET_ADD: net_increase_from_disposal_of_trading_financial_assets
  RECEIVE_INTEREST_FEE_COMMISSION: cash_received_from_interest_fees_and_commissions
  BORROW_FUND_ADD: net_increase_in_borrowed_funds
  REPO_BUSINESS_FUND_ADD: net_increase_in_repurchase_funds
  RECEIVE_TAX_REFUND: tax_refunds_received
  RECEIVE_OTHER_OPERATE: other_cash_received_from_operating_activities
  OPERATE_CASH_IN_BALANCE: subtotal_of_cash_inflows_from_operating_activities
  BUY_SERVICES: cash_paid_for_goods_and_services
  LOAN_ADVANCE_ADD: net_increase_in_customer_loans_and_advances
  DEPOSIT_CENTRAL_BANK_INTERBANK_ADD: net_increase_in_deposits_with_central_bank_and_interbank
  PAY_ORIGINAL_INSURANCE_CLAIM: cash_paid_for_original_insurance_claims
  PAY_INTEREST_FEE_COMMISSION: cash_paid_for_interest_fees_and_commissions
  PAY_POLICY_DIVIDEND: cash_paid_for_policy_dividends
  PAY_STAFF_CASH: cash_paid_to_and_for_employees
  PAY_ALL_TAX: taxes_and_fees_paid
  PAY_OTHER_OPERATE: other_cash_paid_for_operating_activities
  OPERATE_CASH_OUT_BALANCE: subtotal_of_cash_outflows_from_operating_activities
  NETCASH_OPERATE: net_cash_flows_from_operating_activities
  INVEST_CASH_FLOW_BALANCE: cash_flows_from_investing_activities
  WITHDRAW_INVEST: cash_received_from_disposal_of_investments
  RECEIVE_INVEST_INCOME: cash_received_from_investment_income
  DISPOSAL_LONG_ASSET: net_cash_received_from_disposal_of_fixed_intangible_and_other_long_term_assets
  DISPOSAL_SUBSIDIARY_JOINT: net_cash_received_from_disposal_of_subsidiaries_and_other_business_units
  RECEIVE_OTHER_INVEST: other_cash_received_from_investing_activities
  REDUCE_PLEDGE_TIMEDEPOSITS: cash_received_from_decrease_in_pledged_and_time_deposits
  DISPOSAL_AFS_FINASSET_ADD: net_increase_from_disposal_of_afs_financial_assets
  INVEST_CASH_IN_BALANCE: subtotal_of_cash_inflows_from_investing_activities
  CONSTRUCT_LONG_ASSET: cash_paid_for_fixed_intangible_and_other_long_term_assets
  INVEST_PAY_CASH: cash_paid_for_investments
  PLEDGE_LOAN_ADD: net_increase_in_pledged_loans
  OBTAIN_SUBSIDIARY_JOINT: net_cash_paid_for_acquisition_of_subsidiaries_and_other_business_units
  ADD_PLEDGE_TIMEDEPOSITS: cash_paid_for_increase_in_pledged_and_time_deposits
  PAY_OTHER_INVEST: other_cash_paid_for_investing_activities
  INVEST_CASH_OUT_BALANCE: subtotal_of_cash_outflows_from_investing_activities
  NETCASH_INVEST: net_cash_flows_from_investing_activities
  FINANCE_CASH_FLOW_BALANCE: cash_flows_from_financing_activities
  ACCEPT_INVEST_CASH: cash_received_from_capital_contributions
  SUBSIDIARY_ACCEPT_MINORITY_INVEST: cash_received_from_minority_shareholders_of_subsidiaries
  RECEIVE_LOAN_CASH: cash_received_from_borrowings
  ISSUE_BOND: cash_received_from_issuing_bonds
  RECEIVE_OTHER_FINANCE: other_cash_received_from_financing_activities
  FINANCE_CASH_IN_BALANCE: subtotal_of_cash_inflows_from_financing_activities
  PAY_DEBT_CASH: cash_paid_for_debt_repayment
  ASSIGN_DIVIDEND_PROFIT: cash_paid_for_dividends_profits_and_interest
  SUBSIDIARY_PAY_MINORITY_DIVIDEND: dividends_and_profits_paid_to_minority_shareholders_of_subsidiaries
  PAY_OTHER_FINANCE: other_cash_paid_for_financing_activities
  FINANCE_CASH_OUT_BALANCE: subtotal_of_cash_outflows_from_financing_activities
  NETCASH_FINANCE: net_cash_flows_from_financing_activities
  RATE_CHANGE_EFFECT: effect_of_exchange_rate_changes_on_cash
  CCE_ADD: net_increase_in_cash_and_cash_equivalents
  BEGIN_CCE: cash_and_cash_equivalents_at_beginning_of_period
  END_CASH: cash_at_end_of_period
  BEGIN_CASH: cash_at_beginning_of_period
  END_CASH_EQUIVALENTS: cash_equivalents_at_end_of_period
  BEGIN_CASH_EQUIVALENTS: cash_equivalents_at_beginning_of_period
  END_CCE: cash_and_cash_equivalents_at_end_of_period
